### ISSUE TITLE
NexT v7 Docs

### ISSUE THREAD

**Issue by ivan-nginx** [theme-next/theme-next.org#36]
- [x] Elegant and Powerful Theme for Hexo center in `docs/`
- [x] Add Four Schemes pics in `docs/`
- [x] Add Five Code Highlighting Themes pics in `docs/`
- [x] Valine images in `docs/third-party-services/comments-and-widgets/`? @sli1989
- [ ] Added custom language support feature [#253](https://github.com/theme-next/hexo-theme-next/pull/253) doc?
- [x] Related_posts.params in `docs/theme-settings/posts/`?
- [ ] Assets in `docs/theme-settings/` ?
- [ ] Name NexT Configuration to NexT Quick Start in getting-started?
- [ ] Add menu.sitemap doc in `docs/theme-settings/`
- [ ] Move Configuring Menu Items to theme-settings?
- [x] .travis.yml (NexT Deployment in `docs/getting-started/`). Moved into `docs/getting-started/deployment/` page.
- [x] Move all external modules settings into `docs/external-libraries/`.
- [x] macOS `.gitignore` bug (https://github.com/theme-next/hexo-theme-next/issues/37, https://github.com/theme-next/hexo-theme-next/issues/636)
- [x] Warnings about `hexo-renderer-kramed` configuration (https://github.com/theme-next/hexo-theme-next/issues/826)
- [ ] Docs for `header: false` in Front-matter
- [x] Docs for growingio analytics (https://github.com/theme-next/hexo-theme-next/pull/354)

**Comment by ivan-nginx** [comment]
I think better will be on Hexo & NexT, and it's already done (later will be with multilanguage, like Hexo site). The problem is – too many docs & configurations. We working with Alex on it and site will be ASAP. You also can join to working on site, just write me in Telegram, if you want.

**Comment by stevenjoezhang** [comment]
@ivan-nginx How about
moving https://github.com/theme-next/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md
and https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/ALGOLIA-SEARCH.md to https://github.com/theme-next/theme-next-algolia-instant-search;

moving https://github.com/theme-next/hexo-theme-next/blob/master/docs/LEANCLOUD-COUNTER-SECURITY.md
and https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
to https://github.com/theme-next/hexo-leancloud-counter-security
?

Besides, do you think there are too many documents about the licence?
https://github.com/theme-next/hexo-theme-next/blob/master/LICENSE.md
https://github.com/theme-next/hexo-theme-next/blob/master/docs/LICENSE.txt
https://github.com/theme-next/hexo-theme-next/blob/master/docs/AGPL3.md

Maybe we can merge them into a single LICENCE file, and then use an ISSUE to maintain a list of contributor (and credits), just like the v7.x ROADMAP

**Comment by ivan-nginx** [comment]
> @ivan-nginx How about
> moving https://github.com/theme-next/hexo-theme-next/blob/master/docs/ALGOLIA-SEARCH.md
> and https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/ALGOLIA-SEARCH.md to https://github.com/theme-next/theme-next-algolia-instant-search;

~~Yes!~~ Only links to docs website will be enough.

> moving https://github.com/theme-next/hexo-theme-next/blob/master/docs/LEANCLOUD-COUNTER-SECURITY.md
> and https://github.com/theme-next/hexo-theme-next/blob/master/docs/zh-CN/LEANCLOUD-COUNTER-SECURITY.md
> to https://github.com/theme-next/hexo-leancloud-counter-security
> ?

~~Yes!~~ Only links to docs website will be enough.

***

Need to make move like this for all similar docs. For RU docs too.

**Comment by stevenjoezhang** [comment]
Yes, theme-next.org can be multi-language.Translated articles are more friendly to users.

**Comment by stevenjoezhang** [comment]
Besides, do you think there are too many documents about the licence?
https://github.com/theme-next/hexo-theme-next/blob/master/LICENSE.md
https://github.com/theme-next/hexo-theme-next/blob/master/docs/LICENSE.txt
https://github.com/theme-next/hexo-theme-next/blob/master/docs/AGPL3.md
https://github.com/theme-next/hexo-theme-next/blob/master/docs/AUTHORS.md

Maybe we can merge them into a single LICENCE file, and then use an ISSUE to maintain a list of contributor (and credits), just like the v7.x ROADMAP

**Comment by ivan-nginx** [comment]
> Besides, do you think there are too many documents about the licence?
> https://github.com/theme-next/hexo-theme-next/blob/master/LICENSE.md
> https://github.com/theme-next/hexo-theme-next/blob/master/docs/LICENSE.txt
> https://github.com/theme-next/hexo-theme-next/blob/master/docs/AGPL3.md
> 
> Maybe we can merge them into a single LICENCE file, and then use an ISSUE to maintain a list of contributor (and credits), just like the v7.x ROADMAP

I'm right now working on it, not only on License. Don't touch this docs for now.

***

About 

> Yes, theme-next.org can be multi-language. Translated articles are more friendly to users.

Need to move this docs to the site, theme-next.org/docs/..

Actually, some docs already there.

So, my mistake with the question above: https://github.com/theme-next/theme-next.org/issues/36#issuecomment-475950974 – answer is **no**. Need just create link from this repos to site with docs with usage for this module.

**Comment by stevenjoezhang** [comment]
For now it seems fine... there are only docs in English on theme-next.org.
We can deal with the multi-language issues in the future. Lots of work need to do.

**Comment by ivan-nginx** [comment]
@stevenjoezhang first of all, u need to join with any supported messengers for NexT, or suggest another one. I suggest to join in Telegram.

**Comment by stevenjoezhang** [comment]
@ivan-nginx Yes, I have read https://github.com/theme-next/hexo-theme-next/issues/699 and joined the Telegram chat... I'm not very active, just check the message occasionally

**Comment by ivan-nginx** [comment]
@stevenjoezhang please, write me PM in Telegram, I can't to find you there.

**Comment by ivan-nginx** [comment]
@stevenjoezhang so, how we can add to auto-launch this script? Maybe directly in Netlify, this script will be check for new versions and generate if needed?

**Comment by stevenjoezhang** [comment]
> so, how we can add to auto-launch this script?

Perhaps we can use another script to get the update, and then send PR to the repository

**Comment by stevenjoezhang** [comment]
Superseded by #88
